### ISSUE TITLE
HighAccuracyPresetEmitterDisabled.json missing

### ISSUE THREAD

**Issue by hello-binit** [hello-robot/stretch_web_teleop#1]
Launching the web interface gives the following warning:

```
[realsense2_camera_node-1] [WARN] [1702615003.792560477] [camera]: JSON file provided doesn't exist! (/home/hello-robot/ament_ws/install/stretch_core/share/stretch_core/config/HighAccuracyPresetEmitterDisabled.json)
```

[Stretch Core](https://github.com/hello-robot/stretch_ros2/tree/humble/stretch_core/config) doesn't have this file. Could you open a PR on the ROS2 repo to add this config file in?

**Comment by hello-vinitha** [comment]
Fixed in 041b597d31466be91338976cd948a87f9634b1c2
