### ISSUE TITLE
Support Beta Teleop Kit cameras in the interface

### ISSUE THREAD

**Issue by hello-binit** [hello-robot/stretch_web_teleop#18]

**Comment by hello-vinitha** [comment]
Addressed in `beta-teleop` [branch](https://github.com/hello-robot/stretch_web_teleop/tree/beta-teleop) 

This branch relies on changes made in https://github.com/hello-robot/stretch_ros2/pull/105

The launch file currently requires multiple command line arguments for selecting cameras. Before merging https://github.com/hello-robot/stretch_web_teleop/issues/21 should be addressed to automatically select installed cameras.
