### ISSUE TITLE
Load certfile and keyfile parameters automatically

### ISSUE THREAD

**Issue by hello-binit** [hello-robot/stretch_web_teleop#29]
The command for launching the web interface currently looks like:

```
ros2 launch stretch_web_teleop web_interface.launch.py certfile:=${HELLO_FLEET_ID}+6.pem keyfile:=${HELLO_FLEET_ID}+6-key.pem
```

The `certfile` and `keyfile` parameters are required, because the default values for those parameters do not exist.

https://github.com/hello-robot/stretch_web_teleop/blob/449143f73810f5ad72fed94c881282257435bb1a/launch/web_interface.launch.py#L27-L28

The default values for those parameters should be changed to be empty, and the launch file should load `${HELLO_FLEET_ID}+6.pem` and `${HELLO_FLEET_ID}+6-key.pem` if those parameters are empty. Then the command to launch the interface would simply be:

```
ros2 launch stretch_web_teleop web_interface.launch.py
```

**Comment by hello-vinitha** [comment]
Addressed in https://github.com/hello-robot/stretch_web_teleop/commit/e44fb11c56571e1dac353c3d91f20afded273344
